### ISSUE TITLE
Ubuntu 16.04 not connected to Jenkins server

### ISSUE THREAD

**Issue by jpvandy** [sstsimulator/sst-sqe#344]
Started by user Vandyke, John P
[EnvInject] - Loading node environment variables.
Building remotely on SST Ubuntu 16.04 (ubuntu16.04 sstresource) in workspace /home/sstbuild/jenkins/workspace/SST__Ubuntu_16.04_OMPI_1.10_Boost_1.56_mainline
FATAL: java.io.EOFException
hudson.remoting.RequestAbortedException: java.io.EOFException
	at hudson.remoting.Request.abort(Request.java:303)
	at hudson.remoting.Channel.terminate(Channel.java:847)
	at org.jenkinsci.remoting.nio.NioChannelHub$3.run(NioChannelHub.java:614)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:112)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at ......remote call to SST Ubuntu 16.04(Native Method)
	at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1416)
	at hudson.remoting.Request.call(Request.java:172)
	at hudson.remoting.Channel.call(Channel.java:780)
	at hudson.FilePath.act(FilePath.java:979)
	at hudson.FilePath.act(FilePath.java:968)
	at org.jenkinsci.plugins.gitclient.Git.getClient(Git.java:131)
	at hudson.plugins.git.GitSCM.createClient(GitSCM.java:741)
	at hudson.plugins.git.GitSCM.createClient(GitSCM.java:733)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1080)
	at hudson.scm.SCM.checkout(SCM.java:485)
	at hudson.model.AbstractProject.checkout(AbstractProject.java:1269)
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:607)
	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:529)
	at hudson.model.Run.execute(Run.java:1738)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)
Caused by: java.io.EOFException
	at org.jenkinsci.remoting.nio.NioChannelHub$3.run(NioChannelHub.java:614)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:112)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
ERROR: Step ‘Publish JUnit test result report’ failed: no workspace for SST__Ubuntu_16.04_OMPI_1.10_Boost_1.56_mainline #96
ERROR: Step ‘E-mail Notification’ failed: no workspace for SST__Ubuntu_16.04_OMPI_1.10_Boost_1.56_mainline #96
Started calculate disk usage of build
Finished Calculation of disk usage of build in 0 seconds
ERROR: Step ‘Delete workspace when build is done’ failed: no workspace for SST__Ubuntu_16.04_OMPI_1.10_Boost_1.56_mainline #96
Finished: FAILURE

**Comment by jwilso** [comment]
Looking for workaround.  This is a known Jenkins bug.
https://issues.jenkins-ci.org/browse/JENKINS-28086

**Comment by jpvandy** [comment]
jwilso fixed (installed a work around) several days ago.
